### ISSUE TITLE
Can you update chalk?

### ISSUE THREAD

**Issue by Ciantic** [nexdrew/yargonaut#12]
I have a problem way upstream. 

Electron-builder packages chalk 1.1.3 because of this yargonaut, yet everything else depends on chalk 2.x series. This causes electron applications not starting unless I manually update the chalk inside the app.asar file within electron package.

**Comment by jonathan-lg** [comment]
+1

Hey @Ciantic, are you manually performing the update to `chalk`?  ~I've been running into the same thing but I haven't found a way of modifying the app.asar that `electron-builder` creates...~

Update:  I found a `node_modules` folder one level above my project structure, this had an old version of `chalk`.  Once I removed that folder, the errors are resolved and electron is able to pull the `2.x` dependency correctly.

**Comment by Ciantic** [comment]
@jonathan-lg yes I've found workaround too, but for me I had to *add* chalk 2.x to my electron project (even though I didn't use it) so that it would not bundle chalk 1.x version which causes issues. Either way the electron-builder does not bundle both, it just bundles what ever it wants, at least it seems like.

If I manually changed the version from dependencies to 2.x series it also worked. It's a bit pain. I know it's not an issue with the yargonaut, but updating chalk in this project would fix it too for me 👍

**Comment by nexdrew** [comment]
Apologies for the long silence, but I am no longer maintaining yargonaut - I don't even know if it still works with a modern version of yargs. For some background on why this is the case, [please read the discussion here](https://github.com/nexdrew/yargonaut/issues/9#issuecomment-351807371).

I would rather not publish a new version of yargonaut with an upgraded chalk dependency, since that might give the false impression to others that yargonaut is still active/maintained.

Rather, what I would suggest is that, if you're interested, you fork yargonaut, update the dependencies there, and then publish your own version to npm as `@username/yargonaut`. Then you could swap out the original `yargonaut` with your own package in your Electron app, and we could point other people with the same problem to your package.

Otherwise, if you're interested in maintaining yargonaut, I can grant you commit bits on this repository and in the npm registry, or we can figure out another option to transfer ownership.
